/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import StaticsCard from "../components/StaticsCard";
import TestCard from "../components/TestCard";

// import styles from "../styles/Home.module.css";
export default function Home() {
  console.log("object");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar onClick={() => alert("ss")} />
      <div className="px-16 pt-4">
        <div className="flex justify-between z-0 w-full">
          <StaticsCard />
          <TestCard />
        </div>
        <div className="w-full bg-white shadow-inner z-10 mt-5 rounded-lg h-[600px] block p-7 mb-6">
          <div className="flex border-2 w-2/6 h-12 align-middle justify-between flex-wrap items-center px-3 text-base">
            <button>Today's Orders</button>
            <button>Tommorow's Orders</button>
            <button>Custom Orders</button>
          </div>
        </div>
      </div>
    </div>
  );
}
